server:
  port: 8084

spring:
  profiles:
    active: dev
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:29091,127.0.0.1:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    drill:
      url: jdbc:mysql://127.0.0.1:23306/drill?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
      username: nep
      password: nep123
  redis:
  #################redis基础配置#################
    database: 5
    host: 127.0.0.1
    port: 26379
    timeout: 3000
  #################redis线程池设置#################
    pool:
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-active: 2000
      # 连接池中的最大空闲连接，默认值也是8。
      max-idle: 500
      #连接池中的最小空闲连接，默认值也是0。
      min-idle: 50
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 10000